### ISSUE TITLE
Row template with more info like salary range, office location, technologies 

### ISSUE THREAD

**Issue by josealfonsomora** [remote-es/remotes#11]
I think it would be positive to have row as a template to fill company description and also add more information.
```
* Company Name [Open positions](https://positions.url) | Office Location | [Salary€ - Range€] | Technologies  
```

**Comment by acroca** [comment]
As a related idea, we could have a longer section per company. At the moment I don't think the list is grow too much, so having maybe a sort of index and a section per company would make sense to me. Or we can have a `.md` file per company, but I'd prefer to keep it in one page until it's too long.
What do you think?

**Comment by alexpdp7** [comment]
My thought about this was to keep the list to a bare "practical" minimum until we have a significant amount of companies. Right now we have 30 companies, so it's reasonable to go through all of them, go to their open positions page and apply to the ones that look good.

This reduces the issues derived with having outdated information, etc.

However, at some point it will become impractical for users to work through a huge list, and we should add ways to filter.

I think it's worth having the discussion now, though.

My proposal would be to leave the list as-is until we reach 100 companies (this is a number I just made up). I think currently the proposed fields are not worth it right now:

* Office location: this one is "cheap" to add, but I don't really see the value. Why do you want this (considering that one of the conditions to get on the list is that visiting the office shouldn't be mandatory... just an occasional thing)

* Salary range: my issue with this is that if this gets outdated it can be "dangerous" (e.g.: say a company is not getting lots of applicants because they don't pay a lot. They figure this out, but they don't know about this repo and don't submit an update. People could skip applying to the company for low salary... even though they pay well!). What I think could work is noting which companies publish salary ranges in their offers, though

* Tech stacks: easily outdated, although I don't think this is as problematic as salary range. On the other hand, this is something that is nearly always present on the offers...

...

Thoughts? I'm really open to discussion on those fronts. Right now while I would leave the list as-is, I'm quite open to adding office location and a "publishes salary range" tag, but I'd like to hear the rationale about adding fields.

...

As for the future, I'd have an `.md` per-company with some mandatory fields and "free text".

**Comment by josealfonsomora** [comment]
Location of the company is important in terms of main language (Germany, Spain, Italy, UK, etc..) and  taxes US, Europe, Asia
Location is also important for working time, you can expect to work during the evenings if the company is from the US
Technologies are important, they won't change very fast and front end engineers can filter backend companies

The salary range can be used as a filter but I agree that can be outdated soon or not be accurate

**Comment by alexpdp7** [comment]
Note that the primary purpose of this repo is to list companies offering Spanish contracts. If this is not clear enough in the README, that's a bug, and we should fix it!

Also, companies which do not offer Spanish contracts should be removed.

(Otherwise, this repo is useless. If you don't mind working for a foreign company, there are much better resources out there)

Given that, note that then companies listed here are either Spanish companies or they have explicitly opened up a legal entity in Spain to hire. I think that changes the situation a bit:

* Taxes should not be an issue
* Location is still important, but I would understand that most companies hiring in Spain would be OK with people working in Spain's office hours, and if they aren't, it's highly likely that they will state their requirements in the offers.
* Language is also very important, but I would expect most people working in this business have some degree of English knowledge and that companies hiring in Spain won't be extremely picky about people having to speak perfect English.
* Technologies are also important, but that's something I expect to be clearly stated in the offers.

My idea was to reduce the list to a minimum because anyway you have the job listing URL and you can check the details that are important to you in the offers... and with 31 companies right now, you will not waste a lot of time.

Another option is to add a section to the README kinda like:

> Please make a note in the offer if:
>
> * You have work schedule requirements which deviate significantly from Spanish normal office hours
> * You have specific travel requirements (monthly onsites, etc.) which happen more than 3 times a year
> * You require language knowledge other than Spanish and medium English

What do you think?

@acroca , @uesteibar , opinions? I feel this is something that could benefit from a wider agreement.

**Comment by uesteibar** [comment]
I like that last proposal, we can make certain assumptions here as we're only dealing with companies with legal entities in Spain.

I wouldn't add the salary range as this might vary between roles, but I'm fine with having a "public salary range" flag.

I wouldn't overcomplicate the list _until_ it's actually problematic. Once we reach that point we can see what the problem actually is and deal with it.

**Comment by acroca** [comment]
I think some more info would be useful, but I think I also prefer to keep it simple for now, so I'm fine keeping current structure.

**Comment by pablogeek** [comment]
![showme](https://user-images.githubusercontent.com/1773546/73842592-2af25f00-481d-11ea-9ca1-04046233387b.gif)

**Comment by acroca** [comment]
I think the salary range is something that will change often, and also depends on the job positions in the company. I think it's always better to check their website for that.
Companies will not keep this updated, I rather have no data than outdated data.

**Comment by alexpdp7** [comment]
I have made a PR for @acroca and @uesteibar to review; @josealfonsomora feel free to give us further feedback here or there in this ticket, I would prefer to address the issue in a manner that you are OK with, so do not hesitate to discuss.

If there is no further feedback, I'll close this issue in a week. I'll merge the PR a week after anyone of you three approves if there's no other feedback.

**Comment by josealfonsomora** [comment]
Thanks @alexpdp7 all good. I didn't realize at the beginning that this list was meant for Spanish companies operating in Spain. In this scenario, all my requests may not be very helpful and I agree is better to have a minimalism list

**Comment by alexpdp7** [comment]
Cool! I'll close this, let's see if we deal with the PR.

Again, if the intent of the repo is not clear, we might need to clarify that.

**Comment by eduherminio** [comment]
You're getting closer to the made up number @alexpdp7 😆

**Comment by alexpdp7** [comment]
Indeed- see #54 , thanks for the headsup @eduherminio . If anyone wants to join the discussion there, feel free.
